### ISSUE TITLE
我什么时候能像小明一样用上这种高端许可证啊

### ISSUE THREAD

**Issue by Anthony-Hoo** [YuJuncen/verse-of-south-identify-frontend#1]
羡慕啊

**Comment by YuJuncen** [comment]
老嚯只要 f**k 这个仓库就可以立刻用上了（
因为是 do what the f**k you want to 哦（

**Comment by Anthony-Hoo** [comment]
@YuJuncen 我这边吧您的两个*解析成了markdown语法诶
![image](https://user-images.githubusercontent.com/30752208/60573910-1e9bb480-9dab-11e9-8c9f-b5f97571ac87.png)
